name: Run tests

on:
  push:

jobs:
  run-tests-on-ubuntu-22-04-x86_64:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - name: Compile and run C example
        run: bash c-example/build-run.sh

  run-tests-on-ubuntu-22-04-arm:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - name: Compile and run C example
        run: bash c-example/build-run.sh

  run-tests-on-windows-x86_64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - name: Compile and run C example
        shell: powershell
        run: |
          cd c-example
          .\build-run.bat